<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('c')
			->select('COUNT(c)')
			->getQuery()
			->getSingleScalarResult();
	}
}
