<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('p')
			->select('COUNT(p)')
			->getQuery()
			->getSingleScalarResult();
	}

	public function getByUser($user_id, $is_admin) {
		$qb = $this->createQueryBuilder('p')
            ->orderBy('p.name', 'ASC');

        if(!$is_admin) {
            $qb->leftJoin('p.users', 'user')
            ->where($qb->expr()->eq('user.id', $user_id));
        }

        return $qb;
	}
}
