<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('t')
			->select('COUNT(t)')
			->getQuery()
			->getSingleScalarResult();
	}

	public function getTicketsByUserProject($user_id, $limit, $offset) {
		return $this->createQueryBuilder('t')
   			->orderBy('t.id', 'DESC')
        	->leftJoin('t.project', 'p')
        	->leftJoin('p.users', 'user')
			->andWhere($this->createQueryBuilder('t')->expr()->eq('user.id', $user_id))
			->setFirstResult($offset)
			->setMaxResults($limit)
        	->getQuery()->getResult();
	}
}
