<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketStateRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('ts')
			->select('COUNT(ts)')
			->getQuery()
			->getSingleScalarResult();
	}
}
