<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('u')
			->select('COUNT(u)')
			->getQuery()
			->getSingleScalarResult();
	}

	public function findByProject($project_id) {
		$qb = $this->createQueryBuilder('u')
   			->orderBy('u.lastName', 'ASC')
   			->orderBy('u.firstName', 'ASC')
        	->leftJoin('u.projects', 'p');

    	if($project_id) {
			$qb->andWhere($this->createQueryBuilder('u')->expr()->eq('p.id', $project_id));
		}

		return $qb;
	}
}
