<?php

namespace Webaccess\BugtrackerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getTotalNumber() {
		return $this->createQueryBuilder('u')
			->select('COUNT(u)')
			->getQuery()
			->getSingleScalarResult();
	}
}
