jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: /login$
            security: false

        secured_area:
            pattern: ^/
            anonymous: false
            form_login:
                login_path:  webaccess_bugtracker_login
                check_path:  webaccess_bugtracker_login_check
                default_target_path: webaccess_bugtracker_ticket
            logout:
                path: webaccess_bugtracker_logout
                target: /
    access_control:
        - { path: user.*, role: ROLE_ADMIN }
        - { path: company.*, role: ROLE_ADMIN }
        - { path: project.*, role: ROLE_ADMIN }

    providers:
        main:
            entity: { class: WebaccessBugtrackerBundle:User, property: username }

    encoders:
        Webaccess\BugtrackerBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]