parameters:
    symfony.form.class: Symfony\Component\Form\Form

    webaccess_bugtracker.user_manager.class: Webaccess\BugtrackerBundle\Library\UserManager
    webaccess_bugtracker.user.form.class: Webaccess\BugtrackerBundle\Form\Type\UserFormType
    webaccess_bugtracker.user.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\UserFormHandler

    webaccess_bugtracker.project_manager.class: Webaccess\BugtrackerBundle\Library\ProjectManager
    webaccess_bugtracker.project.form.class: Webaccess\BugtrackerBundle\Form\Type\ProjectFormType
    webaccess_bugtracker.project.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\ProjectFormHandler

    webaccess_bugtracker.company_manager.class: Webaccess\BugtrackerBundle\Library\CompanyManager
    webaccess_bugtracker.company.form.class: Webaccess\BugtrackerBundle\Form\Type\CompanyFormType
    webaccess_bugtracker.company.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\CompanyFormHandler

    webaccess_bugtracker.ticket_manager.class: Webaccess\BugtrackerBundle\Library\TicketManager
    webaccess_bugtracker.ticket.form.class: Webaccess\BugtrackerBundle\Form\Type\TicketFormType
    webaccess_bugtracker.ticket.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\TicketFormHandler

    webaccess_bugtracker.ticketstate_manager.class: Webaccess\BugtrackerBundle\Library\TicketStateManager
    webaccess_bugtracker.ticketstate.form.class: Webaccess\BugtrackerBundle\Form\Type\TicketStateFormType
    webaccess_bugtracker.ticketstate.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\TicketStateFormHandler

    webaccess_bugtracker.ticket_filter.form.class: Webaccess\BugtrackerBundle\Form\Type\TicketFilterFormType
    webaccess_bugtracker.ticket_filter.form_handler.class: Webaccess\BugtrackerBundle\Form\Handler\TicketFilterFormHandler

services:
    webaccess_bugtracker.user_manager:
        class: %webaccess_bugtracker.user_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
            encoderFactory: "@security.encoder_factory"
            securityContect: "@security.context"
            session: "@session"

    webaccess_bugtracker.user.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_user
            - webaccess_bugtracker_user

    webaccess_bugtracker.user.form.type:
        class: %webaccess_bugtracker.user.form.class%
        tags:
            - { name: form.type, alias: webaccess_bugtracker_user }

    webaccess_bugtracker.user.form_handler:
        class: %webaccess_bugtracker.user.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.user.form"
            request: "@request"
            userManager: "@webaccess_bugtracker.user_manager"

    webaccess_bugtracker.project_manager:
        class: %webaccess_bugtracker.project_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"

    webaccess_bugtracker.project.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_project
            - webaccess_bugtracker_project

    webaccess_bugtracker.project.form.type:
        class: %webaccess_bugtracker.project.form.class%
        tags:
            - { name: form.type, alias: webaccess_bugtracker_project }

    webaccess_bugtracker.project.form_handler:
        class: %webaccess_bugtracker.project.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.project.form"
            request: "@request"
            projectManager: "@webaccess_bugtracker.project_manager"

    webaccess_bugtracker.company_manager:
        class: %webaccess_bugtracker.company_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"

    webaccess_bugtracker.company.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_company
            - webaccess_bugtracker_company

    webaccess_bugtracker.company.form.type:
        class: %webaccess_bugtracker.company.form.class%
        tags:
            - { name: form.type, alias: webaccess_bugtracker_company }

    webaccess_bugtracker.company.form_handler:
        class: %webaccess_bugtracker.company.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.company.form"
            request: "@request"
            companyManager: "@webaccess_bugtracker.company_manager"

    webaccess_bugtracker.ticket_manager:
        class: %webaccess_bugtracker.ticket_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
            userManager: "@webaccess_bugtracker.user_manager"

    webaccess_bugtracker.ticket.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_ticket
            - webaccess_bugtracker_ticket

    webaccess_bugtracker.ticket.form.type:
        class: %webaccess_bugtracker.ticket.form.class%
        arguments:
            userManager: "@webaccess_bugtracker.user_manager"
            translationManager: "@translator"
        tags:
            - { name: form.type, alias: webaccess_bugtracker_ticket }

    webaccess_bugtracker.ticket.form_handler:
        class: %webaccess_bugtracker.ticket.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.ticket.form"
            request: "@request"
            ticketManager: "@webaccess_bugtracker.ticket_manager"

    webaccess_bugtracker.ticketstate_manager:
        class: %webaccess_bugtracker.ticketstate_manager.class%
        arguments:
            em: "@doctrine.orm.entity_manager"
            userManager: "@webaccess_bugtracker.user_manager"

    webaccess_bugtracker.ticketstate.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_ticketstate
            - webaccess_bugtracker_ticketstate

    webaccess_bugtracker.ticketstate.form.type:
        class: %webaccess_bugtracker.ticketstate.form.class%
        arguments:
            translationManager: "@translator"
            userManager: "@webaccess_bugtracker.user_manager"
        tags:
            - { name: form.type, alias: webaccess_bugtracker_ticketstate }

    webaccess_bugtracker.ticketstate.form_handler:
        class: %webaccess_bugtracker.ticketstate.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.ticketstate.form"
            request: "@request"
            ticketStateManager: "@webaccess_bugtracker.ticketstate_manager"


    webaccess_bugtracker.ticket_filter.form:
        class: %symfony.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - webaccess_bugtracker_ticket_filter
            - webaccess_bugtracker_ticket_filter

    webaccess_bugtracker.ticket_filter.form.type:
        class: %webaccess_bugtracker.ticket_filter.form.class%
        arguments:
            userManager: "@webaccess_bugtracker.user_manager"
            translationManager: "@translator"
        tags:
            - { name: form.type, alias: webaccess_bugtracker_ticket_filter }

    webaccess_bugtracker.ticket_filter.form_handler:
        class: %webaccess_bugtracker.ticket_filter.form_handler.class%
        scope: request
        arguments:
            form: "@webaccess_bugtracker.ticket_filter.form"
            request: "@request"
            session: "@session"

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    webaccess_bugtracker.user_password_change:
        class: Webaccess\BugtrackerBundle\EventListener\UserPasswordChange
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
